context:
  name: apache-airflow-providers-sftp
  version: "5.5.1"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/apache_airflow_providers_sftp-${{ version }}.tar.gz
  sha256: 6d3916a81aec3cb1fcc6ad369fe71c1f3e6e5e5e3a0fff69815913aee9ffc657

build:
  noarch: python
  script: python -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - flit-core ==3.12.0
  run:
    - python >=${{ python_min }}
    - apache-airflow >=2.11.0
    - apache-airflow-providers-ssh >=4.0.0
    - apache-airflow-providers-common-compat >=1.10.1
    - paramiko >=2.9.0,<4.0.0
    - asyncssh >=2.12.0

tests:
  - python:
      imports:
      - airflow.providers.sftp
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  homepage: https://github.com/apache/airflow/
  summary: Provider package apache-airflow-providers-sftp for Apache Airflow
  license: Apache-2.0
  license_file:
    - LICENSE
    - NOTICE
  documentation: https://airflow.apache.org/docs/apache-airflow-providers-sftp/stable/index.html
  repository: https://github.com/apache/airflow/

extra:
  recipe-maintainers:
    - xylar
